import { ChapterModel } from '../viewmodel/ChapterModel'
import { CourseModel } from '../viewmodel/CourseModel'
import { SectionModel } from '../viewmodel/SectionModel'
import { UserModel } from '../viewmodel/UserModel'

export const  CourseListData: Array<CourseModel> = [
  {
    id: "1",
    name: "解码城市人工智能",
    teacher: "张三",
    school: "广软",
    type: "cs",
    introduction: "本课程从国家建构的新视角，采用点线结合、经纬交织的方法，立体地呈现中国共产党近百年的苦难与辉煌在“求历史之实\"的基础上，\"求历史之是”。主要从中西方文明、历史与现实、国共两党等多个角度进行比较，重点分析中华民族的危机与中国共产党的创立、国共竞争与民族复兴的选择、建国执政与中华民族走向复兴、中华民族伟大复兴的新时代等问题，深入阐述为什么没有共产党就没有新中国，为什么只有社会主义才能救中国，为什么只有中国特色社会主义才能发展中国。本课程是中央社会主义学院教学改革“五史合一\"模块的核心课程，两年来已给中央社会主义学院各个干部班次授课百余次，受到学员一致好评。学员评价说:“这堂课刷新了我们以前的认识，党史原来可以这样讲!",
    image: $r('app.media.th'),
  },
  {
    id: "2",
    name: "西部行大讲堂",
    teacher: "张三",
    school: "广软",
    type: "eng",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th1'),
  },
  {
    id: "3",
    name: "AI时代的数字营销",
    teacher: "张三",
    school: "广软",
    type: "other",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th2'),
  },
  {
    id: "4",
    name: "人工智能赋能数字营销",
    teacher: "张三",
    school: "广软",
    type: "math",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th3'),
  },
  {
    id: "5",
    name: "解码城市人工智能",
    teacher: "张三",
    school: "广软",
    type: "cs",
    introduction: "本课程从国家建构的新视角，采用点线结合、经纬交织的方法，立体地呈现中国共产党近百年的苦难与辉煌在“求历史之实\"的基础上，\"求历史之是”。主要从中西方文明、历史与现实、国共两党等多个角度进行比较，重点分析中华民族的危机与中国共产党的创立、国共竞争与民族复兴的选择、建国执政与中华民族走向复兴、中华民族伟大复兴的新时代等问题，深入阐述为什么没有共产党就没有新中国，为什么只有社会主义才能救中国，为什么只有中国特色社会主义才能发展中国。本课程是中央社会主义学院教学改革“五史合一\"模块的核心课程，两年来已给中央社会主义学院各个干部班次授课百余次，受到学员一致好评。学员评价说:“这堂课刷新了我们以前的认识，党史原来可以这样讲!",
    image: $r('app.media.th'),
  },
  {
    id: "6",
    name: "西部行大讲堂",
    teacher: "张三",
    school: "广软",
    type: "eng",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th1'),
  },
  {
    id: "7",
    name: "AI时代的数字营销",
    teacher: "张三",
    school: "广软",
    type: "other",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th2'),
  },
  {
    id: "8",
    name: "人工智能赋能数字营销",
    teacher: "张三",
    school: "广软",
    type: "math",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th3'),
  },
  {
    id: "9",
    name: "解码城市人工智能",
    teacher: "张三",
    school: "广软",
    type: "cs",
    introduction: "本课程从国家建构的新视角，采用点线结合、经纬交织的方法，立体地呈现中国共产党近百年的苦难与辉煌在“求历史之实\"的基础上，\"求历史之是”。主要从中西方文明、历史与现实、国共两党等多个角度进行比较，重点分析中华民族的危机与中国共产党的创立、国共竞争与民族复兴的选择、建国执政与中华民族走向复兴、中华民族伟大复兴的新时代等问题，深入阐述为什么没有共产党就没有新中国，为什么只有社会主义才能救中国，为什么只有中国特色社会主义才能发展中国。本课程是中央社会主义学院教学改革“五史合一\"模块的核心课程，两年来已给中央社会主义学院各个干部班次授课百余次，受到学员一致好评。学员评价说:“这堂课刷新了我们以前的认识，党史原来可以这样讲!",
    image: $r('app.media.th'),
  },
  {
    id: "10",
    name: "西部行大讲堂",
    teacher: "张三",
    school: "广软",
    type: "eng",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th1'),
  },
  {
    id: "11",
    name: "AI时代的数字营销",
    teacher: "张三",
    school: "广软",
    type: "other",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th2'),
  },
  {
    id: "12",
    name: "人工智能赋能数字营销",
    teacher: "张三",
    school: "广软",
    type: "math",
    introduction: "这里是简介12312312312阿斯顿法师打发斯蒂芬",
    image: $r('app.media.th3'),
  }
]

export const UserInfoData: UserModel = {
  id: "1",
  username: "张三",
  password: "123456",
  school: "广州软件学院",
  qualification: "本科",
  email: '123@qq.com',
  region: "广州",
  position: "学生",
  SelectedCourses: []
}

export const ChapterListData: ChapterModel[] = [
  {
    id: '1',
    courseId: '1',
    title: '第一章 绪论',
    chapterOrder: 0,
    // isExpanded: true
  },
  {
    id: '2',
    courseId: '1',
    title: '第二章 test2',
    chapterOrder: 1,
    // isExpanded: true
  },
  {
    id: '3',
    courseId: '1',
    title: '第三章 test3',
    chapterOrder: 2,
    // isExpanded: true
  },
  {
    id: '4',
    courseId: '1',
    title: '第四章 test4',
    chapterOrder: 3,
    // isExpanded: true
  },
  {
    id: '5',
    courseId: '2',
    title: '第一章 绪论',
    chapterOrder: 0,
    // isExpanded: true
  },
  {
    id: '6',
    courseId: '2',
    title: '第二章 test22',
    chapterOrder: 1,
    // isExpanded: true
  },
  {
    id: '7',
    courseId: '2',
    title: '第三章 test33',
    chapterOrder: 2,
    // isExpanded: true
  },
  {
    id: '8',
    courseId: '2',
    title: '第四章 test44',
    chapterOrder: 3,
    // isExpanded: true
  }
]

export const SectionListData: SectionModel[] = [
  {
    id: '1',
    chapterId: '1',
    sectionNumber: '1.1',
    title: '小节标题1',
    sectionOrder: 0,
    type: 1,     // 1 视频 2 文档
    content: 'http://vjs.zencdn.net/v/oceans.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '2',
    chapterId: '1',
    sectionNumber: '1.2',
    title: '小节标题11',
    sectionOrder: 1,
    type: 1,     // 1 视频 2 文档
    content: 'https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-360p.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '3',
    chapterId: '1',
    sectionNumber: '1.3',
    title: '小节标题111',
    sectionOrder: 2,
    type: 1,     // 1 视频 2 文档
    content: 'http://www.w3school.com.cn/example/html5/mov_bbb.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '4',
    chapterId: '2',
    sectionNumber: '2.1',
    title: '小节标题2',
    sectionOrder: 0,
    type: 1,     // 1 视频 2 文档
    content: 'https://www.w3schools.com/html/movie.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '5',
    chapterId: '2',
    sectionNumber: '2.2',
    title: '小节标题22',
    sectionOrder: 1,
    type: 1,     // 1 视频 2 文档
    content: 'https://media.w3.org/2010/05/sintel/trailer.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '6',
    chapterId: '3',
    sectionNumber: '3.1',
    title: '小节标题3',
    sectionOrder: 0,
    type: 1,     // 1 视频 2 文档
    content: 'https://stream7.iqilu.com/10339/upload_transcode/202002/09/20200209105011F0zPoYzHry.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '7',
    chapterId: '4',
    sectionNumber: '4.1',
    title: '小节标题4',
    sectionOrder: 0,
    type: 2,     // 1 视频 2 文档
    content: '在接触他人观点的时候，我们最容易发生轻信的情况是:对方观点，符合我们的逻辑和价值观。而且他们还很自信、很有趣、不仅让我们产生共鸣，也让我们有机会产生“英雄所见略同”之感--确认了我们自己观点同样高明。\n' +
      '这种情况下，我们几乎不会去质疑或反思。但这往往成为发现真相的盲点。\n' +
      '人们为了捍卫自己的观点和信念，坚持错误、死不悔改者，比比皆是，\n' +
      '可是，愿意颠覆既往观念的人，却一直是极少数这不仅需要智慧--了解自己有思维盲点，知道”犯错是发现真相过程中的常态。\n' +
      '更需要自信--不怕承认“我错了”的人，不会把"犯错等同于智力上的“愚蠢”(俗话说智者千虑，必有一失)，不会因此否定自我价值。\n' +
      '可是，如果自己错了却拒绝承认，就等于断绝了一个智力上自我提升的机会。\n' +
      '与此类似的另一种容易发生轻信的情况是:对方的观点，让我们感觉满足和振奋。这往往是因为:对方的观点，增强了我们的自我价值感、或者我们所在族群的自豪感。'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '8',
    chapterId: '5',
    sectionNumber: '1.1',
    title: '小节标题1',
    sectionOrder: 0,
    type: 1,     // 1 视频 2 文档
    content: 'https://stream7.iqilu.com/10339/upload_transcode/202002/09/20200209104902N3v5Vpxuvb.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '9',
    chapterId: '5',
    sectionNumber: '1.2',
    title: '小节标题11',
    sectionOrder: 1,
    type: 1,     // 1 视频 2 文档
    content: 'http://vjs.zencdn.net/v/oceans.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '10',
    chapterId: '5',
    sectionNumber: '1.3',
    title: '小节标题111',
    sectionOrder: 2,
    type: 1,     // 1 视频 2 文档
    content: 'https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-360p.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '11',
    chapterId: '6',
    sectionNumber: '2.1',
    title: '小节标题2',
    sectionOrder: 0,
    type: 1,     // 1 视频 2 文档
    content: 'http://www.w3school.com.cn/example/html5/mov_bbb.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '12',
    chapterId: '6',
    sectionNumber: '2.2',
    title: '小节标题22',
    sectionOrder: 1,
    type: 1,     // 1 视频 2 文档
    content: 'https://www.w3schools.com/html/movie.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '13',
    chapterId: '7',
    sectionNumber: '3.1',
    title: '小节标题3',
    sectionOrder: 0,
    type: 1,     // 1 视频 2 文档
    content: 'https://media.w3.org/2010/05/sintel/trailer.mp4'  // type =? 1: 视频地址 2: 文档内容
  },
  {
    id: '14',
    chapterId: '8',
    sectionNumber: '4.1',
    title: '222小节标题4',
    sectionOrder: 0,
    type: 2,     // 1 视频 2 文档
    content: '在接触他人观点的时候，我们最容易发生轻信的情况是:对方观点，符合我们的逻辑和价值观。而且他们还很自信、很有趣、不仅让我们产生共鸣，也让我们有机会产生“英雄所见略同”之感--确认了我们自己观点同样高明。\\n\' +\n' +
      '      \'这种情况下，我们几乎不会去质疑或反思。但这往往成为发现真相的盲点。\\n\' +\n' +
      '      \'人们为了捍卫自己的观点和信念，坚持错误、死不悔改者，比比皆是，\\n\' +\n' +
      '      \'可是，愿意颠覆既往观念的人，却一直是极少数这不仅需要智慧--了解自己有思维盲点，知道”犯错是发现真相过程中的常态。\\n\' +\n' +
      '      \'更需要自信--不怕承认“我错了”的人，不会把"犯错等同于智力上的“愚蠢”(俗话说智者千虑，必有一失)，不会因此否定自我价值。\\n\' +\n' +
      '      \'可是，如果自己错了却拒绝承认，就等于断绝了一个智力上自我提升的机会。\\n\' +\n' +
      '      \'与此类似的另一种容易发生轻信的情况是:对方的观点，让我们感觉满足和振奋。这往往是因为:对方的观点，增强了我们的自我价值感、或者我们所在族群的自豪感。'  // type =? 1: 视频地址 2: 文档内容
  },
]